from dataclasses import dataclass
from typing import Dict, Optional


@dataclass(frozen=True)
class MatchingScore:
    """
    Represents the scoring result between a candidate and a job.

    This model stores intermediate and final scores
    generated by matching strategies.
    """

    candidate_id: str
    job_id: str

    overall_score: float
    confidence_score: float

    skill_score: Optional[float] = None
    semantic_score: Optional[float] = None

    explanation: Optional[Dict[str, str]] = None
    confidence_score: float